import fs from 'fs';
import path from 'path';
import OpenAI from 'openai';

let openai = null;

function getClient() {
  if (!openai) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey || apiKey.length < 20) return null;
    openai = new OpenAI({ apiKey });
  }
  return openai;
}

/**
 * Reads project overview files (README.md, package.json).
 */
function getProjectContext(clonePath) {
  let readme = '';
  let packageJson = '';

  try {
    const readmePath = [
      path.join(clonePath, 'README.md'),
      path.join(clonePath, 'readme.md'),
      path.join(clonePath, 'Readme.md')
    ].find(p => fs.existsSync(p));
    
    if (readmePath) {
      readme = fs.readFileSync(readmePath, 'utf8').substring(0, 3000);
    }
  } catch (e) {}

  try {
    const pkgPath = path.join(clonePath, 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      packageJson = JSON.stringify({
        name: pkg.name,
        description: pkg.description,
        dependencies: pkg.dependencies || {},
        scripts: pkg.scripts || {}
      }, null, 2).substring(0, 2000);
    }
  } catch (e) {}

  return { readme, packageJson };
}

/**
 * Generates an overall repository summary (structured + human readable)
 * and improvement suggestions, based on the README, package.json, and the 
 * top file summaries generated by the AI so far.
 */
export async function summarizeRepo(clonePath, fileSummaries, classifications) {
  const context = getProjectContext(clonePath);
  const client = getClient();

  const fallbackResponse = {
    name: "Analyzed Repository",
    purpose: "An application whose exact purpose could not be determined automatically.",
    architecture: "Standard Node.js application",
    components: "Various components and utilities",
    data_flow: "Data flows through defined standard modules.",
    key_files: "See impact score rankings for key files.",
    patterns: "Standard Javascript patterns",
    humanSummary: "This repository has been analyzed, but a full AI summary could not be generated (OpenAI client unavailable or failed).",
    suggestions: ["Ensure OpenAI API key is configured for deeper insights", "Regularly refactor large utility files"]
  };

  if (!client) {
    return fallbackResponse;
  }

  // Create a digest of the top most impactful files to give the LLM context
  const topFiles = Object.entries(fileSummaries)
    .slice(0, 10)
    .map(([filepath, summary]) => `${filepath}: ${summary}`)
    .join('\n');

  const prompt = `You are a Senior Software Architect analyzing a code repository.
I will provide you with the README, the package.json subset, and summaries of the top 10 most impactful files.

Your task is to return a JSON object describing the entire repository with the following STRICT keys:
{
  "name": "Short name of the project based on package.json/README",
  "purpose": "1-sentence description of what this project does",
  "architecture": "High-level architectural pattern (e.g., React Frontend, Express API)",
  "components": "Major components discovered",
  "data_flow": "How data moves through the app",
  "key_files": "Which files are the backbone of the app",
  "patterns": "Observable design patterns (e.g. Hooks, MVC)",
  "humanSummary": "A beautifully written, comprehensive 1-paragraph summary of the repository that a developer would read to instantly understand what they are looking at.",
  "suggestions": ["An array of 3 exact bullet points on how to improve this codebase based on what you see (e.g., technical debt, structure)"]
}

--- Data ---
README excerpt:
${context.readme || "None"}

Package.json excerpt:
${context.packageJson || "None"}

Top File Summaries:
${topFiles}
`;

  try {
    const response = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      response_format: { type: "json_object" },
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 1500,
      temperature: 0.3
    });

    const parsed = JSON.parse(response.choices[0].message.content);
    return parsed;
  } catch (err) {
    console.error('❌ Repo summarizer error:', err.message);
    return fallbackResponse;
  }
}
